### model
model_name_or_path: /x22221259/jcx/para/qwen2.5-7b
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: ptuning

### dataset
dataset: train_data_cypher-title
template: chatml
cutoff_len: 3072
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /x22221259/jcx/paper_result/train-qwen2.5-7b/ptuning_len32
logging_steps: 10
save_steps: 820
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 6
learning_rate: 2.0e-4
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
